### ISSUE TITLE
Does not work for HTTPS 

### ISSUE THREAD

**Issue by aliraza0337** [allfro/pymiproxy#7] opened 2015-05-30 10:16 UTC
I am not able to run it for HTTPS. Can you please guide me if there is some additional effort to run this for HTTPs as well. for HTTP its working fine.

**Comment by eamonnfaherty-productmadness** [comment] 2015-07-02 10:17
+1

When intercepting HTTPS traffic it is still encrypted.

**Comment by allfro** [comment] 2015-07-02 16:07
Could you please let me know what steps you've taken to produce the issue? In order to get SSL interception to work you'll need to import the generated CA file and point your browser's SSL proxy settings to the proxy.

**Comment by mk-pmb** [comment] 2017-05-07 14:59
Is this still an issue?

**Comment by allfro** [comment] 2017-05-07 15:36
I still haven't gotten any repro steps, unfortunately.

**Comment by allfro** [comment] 2017-05-07 16:10
I have tested both examples provided in the `README.md` and imported the generated `ca.pem` file into my Firefox trusted certificate store and I have been able to peek at the requests flowing through the proxy over HTTPS. Here's a sample:

```bash
$ python example1.py
127.0.0.1 - - [07/May/2017 12:07:48] "CONNECT letsencrypt.org:443 HTTP/1.1" 200 -
>> 'GET / HTTP/1.1\r\nHost: letsencrypt.org\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nCookie: _ga=GA1.2.242779816.1494173083; _gid=GA1.2.65941561.1494173227; _gat=1\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nIf-Modified-Since: Sat, 06 May 2017 23:00:03 GMT\r\nIf-None-Match: W/"590e5573-48e2"\r\nCache-Control: max-age=0\r\n\r\n'
```

As you can see, the `CONNECT` line is displayed which indicates the start of encryption. The second line is the `GET` request flowing through that encrypted tunnel with all the headers. I'm not sure what the issue is? I will be closing this issue until further information is provided.

**Closed by allfro** 2017-05-07 16:10 UTC
